<Project Sdk="Microsoft.NET.Sdk">

  <!-- CAE-AOE-V1.0, Audio Object Editing: edits Basic Audio Objects and composes
       Basic and full Audio Objects into Audio Objects, in Shared Storage. -->

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\Mpai.Core.csproj" />
    <ProjectReference Include="..\..\..\..\AIF\Controller\AIF.Controller.csproj" />
    <ProjectReference Include="..\..\..\..\AIF\Communication\SharedStorage\AIF.SharedStorage.csproj" />
  </ItemGroup>

</Project>
