<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Mpai.Cae.Qcv</AssemblyName>
    <RootNamespace>Mpai.Cae.Qcv</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\AIF\Controller\AIF.Controller.csproj" />
    <ProjectReference Include="..\..\..\..\AIF\Store\AIF.Store.csproj" />
    <ProjectReference Include="..\..\..\Core\Mpai.Core.csproj" />
  </ItemGroup>
</Project>
